"use client";

/**
 * Wizard Step 7: Review & Preview.
 *
 * Displays a metadata summary (title, project type, stack) and a
 * markdown body preview generated by generateIdeaBody. This is a
 * read-only step -- the user reviews what will be stored before
 * confirming creation.
 *
 * The preview uses the SAME generateIdeaBody function that will be
 * used during submission, ensuring accuracy.
 */

import type { WizardData } from "./wizard-types";
import { generateIdeaBody } from "./generate-idea-body";

interface WizardStepReviewProps {
  data: WizardData;
}

export function WizardStepReview({ data }: WizardStepReviewProps) {
  const body = generateIdeaBody(data);

  return (
    <div className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold">Review & Preview</h2>
        <p className="text-sm text-muted-foreground">
          Review your idea before creating it.
        </p>
      </div>

      {/* Metadata summary */}
      <div className="space-y-2 rounded-md border p-4">
        <div className="flex items-center gap-2">
          <span className="font-semibold">{data.title}</span>
        </div>
        <div className="flex items-center gap-2">
          <span className="rounded bg-muted px-2 py-0.5 text-sm font-medium">
            {data.projectType}
          </span>
          {data.stack.map((tech) => (
            <span key={tech} className="rounded bg-muted px-2 py-0.5 text-sm">
              {tech}
            </span>
          ))}
        </div>
      </div>

      <hr className="border-border" />

      {/* Body preview */}
      <div className="space-y-2">
        <h3 className="text-sm font-medium">Body Preview</h3>
        {body ? (
          <pre className="whitespace-pre-wrap rounded-md bg-muted p-4 font-mono text-sm">
            {body}
          </pre>
        ) : (
          <p className="text-sm text-muted-foreground">
            No body content - only title and metadata will be saved
          </p>
        )}
      </div>
    </div>
  );
}
