/**
 * Reader for the portfolio-level TODAYS_DIRECTIONS.md file.
 *
 * The file lives outside any individual project (default
 * `~/projects/TODAYS_DIRECTIONS.md`) and is generated by an
 * orchestrator agent the user runs from `~/projects`. It is
 * rendered on the `/today` dashboard page; the body is preserved as
 * opaque markdown for display, and QA checkbox refs are extracted so
 * the UI can wire them to the existing approveQaItem flow.
 */

import { readFile } from "node:fs/promises";
import matter from "gray-matter";
import { expandTilde } from "@/lib/fs/discovery";
import {
  validateTodayDirectionsFrontmatter,
  type TodayDirectionsFrontmatter,
} from "@/lib/schemas/today-directions";

/** Default location of the directions file relative to the home directory. */
export const DEFAULT_TODAY_DIRECTIONS_PATH =
  "~/projects/TODAYS_DIRECTIONS.md";

/**
 * A single QA checkbox reference extracted from the directions body.
 * `checked` reflects the directions file's local state; the canonical
 * QA status lives in the project's QA.md.
 */
export interface TodayDirectionsQaRef {
  qaId: string;
  slug: string;
  checked: boolean;
  /** Display text after the comment marker on the same checkbox line. */
  description: string;
}

export interface TodayDirections {
  frontmatter: TodayDirectionsFrontmatter;
  /** Body markdown after the frontmatter, preserved verbatim for rendering. */
  body: string;
  /** Resolved absolute path the file was read from. */
  filePath: string;
  /** Ordered list of QA checkbox references found in the body. */
  qaRefs: TodayDirectionsQaRef[];
}

interface GetTodayDirectionsOptions {
  /** Override the default path. Tilde-expansion still applies. */
  pathOverride?: string;
}

/**
 * Match a checkbox line carrying a QA reference comment marker.
 * Permissive on leading whitespace so nested lists still match.
 *
 * Capture groups: 1=checkmark char, 2=QA id, 3=project slug, 4=description
 */
const QA_REF_LINE_RE =
  /^\s*[-*]\s+\[([ xX])\]\s+<!--\s*ref:(q_[a-z0-9]{5})\s+slug:([^\s-]+(?:[a-z0-9-_]+)?)\s*-->\s*(.*)$/;

/** Strict QA-id format check: `q_` followed by exactly 5 [a-z0-9]. */
const QA_ID_RE = /^q_[a-z0-9]{5}$/;

/**
 * Walk a markdown body and pull every QA checkbox reference.
 * Lines without a ref marker (`<!-- ref:q_xxxxx slug:project -->`) are skipped.
 */
export function extractQaRefs(body: string): TodayDirectionsQaRef[] {
  const refs: TodayDirectionsQaRef[] = [];
  for (const line of body.split(/\r?\n/)) {
    const match = line.match(QA_REF_LINE_RE);
    if (!match) continue;
    const [, checkChar, qaId, slug, description] = match;
    if (!QA_ID_RE.test(qaId)) continue;
    refs.push({
      qaId,
      slug,
      checked: checkChar === "x" || checkChar === "X",
      description: description.trim(),
    });
  }
  return refs;
}

/**
 * Read and parse the portfolio-level directions file.
 *
 * Returns null on any of: file missing, read error, frontmatter
 * validation failure. Callers render an empty state in that case.
 */
export async function getTodayDirections(
  options: GetTodayDirectionsOptions = {},
): Promise<TodayDirections | null> {
  const filePath = expandTilde(
    options.pathOverride ?? DEFAULT_TODAY_DIRECTIONS_PATH,
  );

  let raw: string;
  try {
    raw = await readFile(filePath, "utf-8");
  } catch {
    return null;
  }

  const normalized = raw.replace(/\r\n/g, "\n");
  const { data, content } = matter(normalized);
  const processed = postProcessFrontmatter(data as Record<string, unknown>);

  const validation = validateTodayDirectionsFrontmatter(processed);
  if (!validation.success) return null;

  return {
    frontmatter: validation.data,
    body: content.trim(),
    filePath,
    qaRefs: extractQaRefs(content),
  };
}

/**
 * gray-matter coerces ISO datetime strings into Date objects when they
 * appear bare in YAML. Mirror the QA/roadmap parsers and re-stringify
 * those fields so Zod's datetime validator sees what it expects.
 */
function postProcessFrontmatter(
  raw: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...raw };
  if (out.generated instanceof Date) {
    out.generated = out.generated.toISOString();
  }
  if (out.for_date instanceof Date) {
    const date = out.for_date as Date;
    const year = date.getUTCFullYear();
    const month = String(date.getUTCMonth() + 1).padStart(2, "0");
    const day = String(date.getUTCDate()).padStart(2, "0");
    out.for_date = `${year}-${month}-${day}`;
  }
  return out;
}
